### PR TITLE
Options helper classes

### PR DESCRIPTION
**Pull request by mharshe**

### CODE REVIEW

**Comment by mharshe** [comment]
Python API for Options class remains unchanged with this. This adds the backend functionality and the next step is to expose these new classes via python and add unit tests for them.

**Review by NightTsarina — APPROVED** [review]
LGTM. But I recommend not merging until you merge the base PR, to ease reviews.

**Comment by NightTsarina** [comment]
Another thing: you say here that the next step is to expose these classes to python, but the next PR in this chain is the TransactionDB support. Is this coming later?

**Comment by mharshe** [comment]
> Another thing: you say here that the next step is to expose these classes to python, but the next PR in this chain is the TransactionDB support. Is this coming later?

Yes, since adding this support to the python API is more boilerplate to the _rocksdb.pyx (which is already a very large file), I decided to focus on the TransactionDB first.

**Review by dato — APPROVED** [review]

**Pull request merged**
